[package]
name = "rust-flagsmith"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
redis = "0.27.5"
dotenv = "0.15.0"
serde = "1.0.215"
flagsmith = "2.0.0"
