# https://taskfile.dev

version: "3"

tasks:
  up:
    cmds:
      - docker compose up --build -d
    silent: true
  down:
    cmds:
      - docker compose down
  local:
    cmds:
      - cargo watch -x run -w src
  build:
    cmds:
      - cargo build
  lint:
    cmds:
      - cargo clippy
    deps:
      - build
  lint-fix:
    cmds:
      - cargo clippy --fix
    deps:
      - build
  db:
    cmds:
      - docker build -t rust-flagsmith .
  dr:
    cmds:
      - docker run -p 8080:8080 --env-file ./.env rust-flagsmith
